name: Build MOS

on:
  push:

jobs:
  build:
    name: Build MOS ${{matrix.target}} (${{matrix.build_type}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [multiboot, multiboot_iso]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt update
          sudo apt -y install nasm grub2-common mtools jq gcc-i686-linux-gnu g++-i686-linux-gnu ninja-build

      - name: Configure CMake
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -B ${{github.workspace}}/build \
            -G Ninja

      - name: Get Bootable File
        id: get_bootable
        run: |
          export BOOTABLE=$(jq -r .${{matrix.target}} < ${{github.workspace}}/build/bootables.json)
          echo "::set-output name=bootable::$BOOTABLE"

      - name: Build
        run: |
          cd ${{github.workspace}}/build
          ninja
          ninja ${{matrix.target}}

      - name: Run Tests
        run: |
          cd ${{github.workspace}}/build
          ctest --output-on-failure

      - name: Upload Bootable Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MOS-${{matrix.target}}-${{matrix.build_type}}
          path: ${{steps.get_bootable.outputs.bootable}}
